name: Latest johncms news workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest news
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "JOHNCMS-NEWS"
          feed_list: "https://johncms.com/rss/"
          committer_username: "gingbot"
