name: SSH

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Setup password
      run: |
        sudo useradd gingdev
        echo gingdev:gingdev123 | sudo chpasswd
        sudo usermod -aG sudo gingdev
    - name: Download & unzip ngrok 
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        ./ngrok authtoken 7wxpKJiTdqpZBaL6YBQNm_35egEEeDabpcw8eeDHDGh
    - name: Run ngrok
      run:
        ./ngrok tcp 22
